# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a15013e79ade0999ccb9004b47b43144fccc1dee383432a99890e795576b4bedb4802c696be5716a9e23ca3d157712387abb402fc51a8d430074708740e901

test:
  secret_key_base: e17d72bee2d63e95d2b6f8992ce2809d31c84f601316684383ad442311fc5f714204cdbfec896662f5ef969aeff6fcbe3687c0a6a3347dc87a5193e077fe665b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
